package dev.persiantools.usecases.collections;

import dev.persiantools.commons.*;

import java.util.*;
import java.util.stream.Collectors;

public class HometownCollection {

    private static HometownCollection instance;
    private final List<Hometown> hometowns;

    private HometownCollection() {
        hometowns = new ArrayList<>();
    }

    public static HometownCollection getInstance() {
        if (instance == null) {
            synchronized (HometownCollection.class) {
                if (instance == null) {
                    instance = new HometownCollection();
                    instance.addHometowns();
                }
            }
        }
        return instance;
    }

    public List<Hometown> find(String code) {
        return this.hometowns
                .stream()
                .filter(h -> h.getCode().equals(code))
                .collect(Collectors.toList());
    }

    private void addHometowns() {

        hometowns.add(new Hometown("169", "آذرشهر", "آذربایجان شرقی"));
        hometowns.add(new Hometown("170", "اسکو", "آذربایجان شرقی"));
        hometowns.add(new Hometown("149", "اهر", "آذربایجان شرقی"));
        hometowns.add(new Hometown("150", "اهر", "آذربایجان شرقی"));
        hometowns.add(new Hometown("171", "بستان آباد", "آذربایجان شرقی"));
        hometowns.add(new Hometown("168", "بناب", "آذربایجان شرقی"));
        hometowns.add(new Hometown("136", "تبریز", "آذربایجان شرقی"));
        hometowns.add(new Hometown("137", "تبریز", "آذربایجان شرقی"));
        hometowns.add(new Hometown("138", "تبریز", "آذربایجان شرقی"));
        hometowns.add(new Hometown("545", "ترکمانچای", "آذربایجان شرقی"));
        hometowns.add(new Hometown("505", "جلفا", "آذربایجان شرقی"));
        hometowns.add(new Hometown("636", "چاروایماق", "آذربایجان شرقی"));
        hometowns.add(new Hometown("164", "سراب", "آذربایجان شرقی"));
        hometowns.add(new Hometown("165", "سراب", "آذربایجان شرقی"));
        hometowns.add(new Hometown("172", "شبستر", "آذربایجان شرقی"));
        hometowns.add(new Hometown("623", "صوفیان", "آذربایجان شرقی"));
        hometowns.add(new Hometown("506", "عجب شیر", "آذربایجان شرقی"));
        hometowns.add(new Hometown("519", "کلیبر", "آذربایجان شرقی"));
        hometowns.add(new Hometown("154", "مراغه", "آذربایجان شرقی"));
        hometowns.add(new Hometown("155", "مراغه", "آذربایجان شرقی"));
        hometowns.add(new Hometown("567", "ورزقان", "آذربایجان شرقی"));
        hometowns.add(new Hometown("173", "هریس", "آذربایجان شرقی"));
        hometowns.add(new Hometown("159", "هشترود", "آذربایجان شرقی"));
        hometowns.add(new Hometown("160", "هشترود", "آذربایجان شرقی"));
        hometowns.add(new Hometown("604", "هوراند", "آذربایجان شرقی"));
        hometowns.add(new Hometown("274", "ارومیه", "آذربایجان غربی"));
        hometowns.add(new Hometown("275", "ارومیه", "آذربایجان غربی"));
        hometowns.add(new Hometown("295", "اشنویه", "آذربایجان غربی"));
        hometowns.add(new Hometown("637", "انزل", "آذربایجان غربی"));
        hometowns.add(new Hometown("292", "بوکان", "آذربایجان غربی"));
        hometowns.add(new Hometown("492", "پلدشت", "آذربایجان غربی"));
        hometowns.add(new Hometown("289", "پیرانشهر", "آذربایجان غربی"));
        hometowns.add(new Hometown("677", "تخت سلیمان", "آذربایجان غربی"));
        hometowns.add(new Hometown("294", "تکاب", "آذربایجان غربی"));
        hometowns.add(new Hometown("493", "چایپاره", "آذربایجان غربی"));
        hometowns.add(new Hometown("279", "خوی", "آذربایجان غربی"));
        hometowns.add(new Hometown("280", "خوی", "آذربایجان غربی"));
        hometowns.add(new Hometown("288", "سردشت", "آذربایجان غربی"));
        hometowns.add(new Hometown("284", "سلماس", "آذربایجان غربی"));
        hometowns.add(new Hometown("285", "سلماس", "آذربایجان غربی"));
        hometowns.add(new Hometown("638", "سیلوانه", "آذربایجان غربی"));
        hometowns.add(new Hometown("291", "سیه چشمه(چالدران)", "آذربایجان غربی"));
        hometowns.add(new Hometown("640", "شوط", "آذربایجان غربی"));
        hometowns.add(new Hometown("293", "شاهین دژ", "آذربایجان غربی"));
        hometowns.add(new Hometown("675", "کشاورز", "آذربایجان غربی"));
        hometowns.add(new Hometown("282", "ماکو", "آذربایجان غربی"));
        hometowns.add(new Hometown("283", "ماکو", "آذربایجان غربی"));
        hometowns.add(new Hometown("286", "مهاباد", "آذربایجان غربی"));
        hometowns.add(new Hometown("287", "مهاباد", "آذربایجان غربی"));
        hometowns.add(new Hometown("296", "میاندوآب", "آذربایجان غربی"));
        hometowns.add(new Hometown("297", "میاندوآب", "آذربایجان غربی"));
        hometowns.add(new Hometown("290", "نقده", "آذربایجان غربی"));
        hometowns.add(new Hometown("400", "اسدآباد", "همدان"));
        hometowns.add(new Hometown("401", "اسدآباد", "همدان"));
        hometowns.add(new Hometown("404", "بهار", "همدان"));
        hometowns.add(new Hometown("405", "بهار", "همدان"));
        hometowns.add(new Hometown("397", "تویسرکان", "همدان"));
        hometowns.add(new Hometown("398", "رزن", "همدان"));
        hometowns.add(new Hometown("399", "رزن", "همدان"));
        hometowns.add(new Hometown("647", "شراء و پیشخوار", "همدان"));
        hometowns.add(new Hometown("502", "فامنین", "همدان"));
        hometowns.add(new Hometown("584", "قلقل رود", "همدان"));
        hometowns.add(new Hometown("402", "کبودرآهنگ", "همدان"));
        hometowns.add(new Hometown("403", "کبودرآهنگ", "همدان"));
        hometowns.add(new Hometown("392", "ملایر", "همدان"));
        hometowns.add(new Hometown("393", "ملایر", "همدان"));
        hometowns.add(new Hometown("395", "نهاوند", "همدان"));
        hometowns.add(new Hometown("396", "نهاوند", "همدان"));
        hometowns.add(new Hometown("386", "همدان", "همدان"));
        hometowns.add(new Hometown("387", "همدان", "همدان"));
        hometowns.add(new Hometown("503", "ابرکوه", "یزد"));
        hometowns.add(new Hometown("444", "اردکان", "یزد"));
        hometowns.add(new Hometown("551", "اشکذر", "یزد"));
        hometowns.add(new Hometown("447", "بافق", "یزد"));
        hometowns.add(new Hometown("561", "بهاباد", "یزد"));
        hometowns.add(new Hometown("445", "تفت", "یزد"));
        hometowns.add(new Hometown("718", "دستگردان", "یزد"));
        hometowns.add(new Hometown("083", "طبس", "یزد"));
        hometowns.add(new Hometown("446", "مهریز", "یزد"));
        hometowns.add(new Hometown("448", "میبد", "یزد"));
        hometowns.add(new Hometown("552", "نیر", "یزد"));
        hometowns.add(new Hometown("543", "هرات و مروست", "یزد"));
        hometowns.add(new Hometown("442", "یزد", "یزد"));
        hometowns.add(new Hometown("443", "یزد", "یزد"));
        hometowns.add(new Hometown("051", "آشتیان", "مرکزی"));
        hometowns.add(new Hometown("052", "اراک", "مرکزی"));
        hometowns.add(new Hometown("053", "اراک", "مرکزی"));
        hometowns.add(new Hometown("058", "تفرش", "مرکزی"));
        hometowns.add(new Hometown("055", "خمین", "مرکزی"));
        hometowns.add(new Hometown("617", "خنداب", "مرکزی"));
        hometowns.add(new Hometown("057", "دلیجان", "مرکزی"));
        hometowns.add(new Hometown("618", "زرند مرکزی", "مرکزی"));
        hometowns.add(new Hometown("059", "ساوه", "مرکزی"));
        hometowns.add(new Hometown("060", "ساوه", "مرکزی"));
        hometowns.add(new Hometown("061", "سربند", "مرکزی"));
        hometowns.add(new Hometown("062", "سربند", "مرکزی"));
        hometowns.add(new Hometown("544", "فراهان", "مرکزی"));
        hometowns.add(new Hometown("056", "محلات", "مرکزی"));
        hometowns.add(new Hometown("571", "وفس", "مرکزی"));
        hometowns.add(new Hometown("593", "هندودر", "مرکزی"));
        hometowns.add(new Hometown("667", "ابوموسی", "هرمزگان"));
        hometowns.add(new Hometown("348", "بستک", "هرمزگان"));
        hometowns.add(new Hometown("586", "بشاگرد", "هرمزگان"));
        hometowns.add(new Hometown("338", "بندرعباس", "هرمزگان"));
        hometowns.add(new Hometown("339", "بندرعباس", "هرمزگان"));
        hometowns.add(new Hometown("343", "بندرلنگه", "هرمزگان"));
        hometowns.add(new Hometown("344", "بندرلنگه", "هرمزگان"));
        hometowns.add(new Hometown("346", "جاسک", "هرمزگان"));
        hometowns.add(new Hometown("337", "حاجی آباد", "هرمزگان"));
        hometowns.add(new Hometown("554", "خمیر", "هرمزگان"));
        hometowns.add(new Hometown("469", "رودان", "هرمزگان"));
        hometowns.add(new Hometown("537", "فین", "هرمزگان"));
        hometowns.add(new Hometown("345", "قشم", "هرمزگان"));
        hometowns.add(new Hometown("470", "گاوبندی", "هرمزگان"));
        hometowns.add(new Hometown("341", "میناب", "هرمزگان"));
        hometowns.add(new Hometown("342", "میناب", "هرمزگان"));
        hometowns.add(new Hometown("483", "ازنا", "لرستان"));
        hometowns.add(new Hometown("484", "ازنا", "لرستان"));
        hometowns.add(new Hometown("557", "اشترینان", "لرستان"));
        hometowns.add(new Hometown("418", "الشتر", "لرستان"));
        hometowns.add(new Hometown("416", "الیگودرز", "لرستان"));
        hometowns.add(new Hometown("417", "الیگودرز", "لرستان"));
        hometowns.add(new Hometown("412", "بروجرد", "لرستان"));
        hometowns.add(new Hometown("413", "بروجرد", "لرستان"));
        hometowns.add(new Hometown("592", "پاپی", "لرستان"));
        hometowns.add(new Hometown("612", "چغلوندی", "لرستان"));
        hometowns.add(new Hometown("613", "چگنی", "لرستان"));
        hometowns.add(new Hometown("406", "خرم آباد", "لرستان"));
        hometowns.add(new Hometown("407", "خرم آباد", "لرستان"));
        hometowns.add(new Hometown("421", "دورود", "لرستان"));
        hometowns.add(new Hometown("598", "رومشکان", "لرستان"));
        hometowns.add(new Hometown("419", "کوهدشت", "لرستان"));
        hometowns.add(new Hometown("385", "ملاوی(پلدختر)", "لرستان"));
        hometowns.add(new Hometown("420", "نورآباد(دلفان)", "لرستان"));
        hometowns.add(new Hometown("528", "ویسیان", "لرستان"));
        hometowns.add(new Hometown("213", "آمل", "مازندران"));
        hometowns.add(new Hometown("214", "آمل", "مازندران"));
        hometowns.add(new Hometown("205", "بابل", "مازندران"));
        hometowns.add(new Hometown("206", "بابل", "مازندران"));
        hometowns.add(new Hometown("498", "بابل", "مازندران"));
        hometowns.add(new Hometown("568", "بندپی", "مازندران"));
        hometowns.add(new Hometown("711", "بندپی شرقی", "مازندران"));
        hometowns.add(new Hometown("217", "بهشهر", "مازندران"));
        hometowns.add(new Hometown("218", "بهشهر", "مازندران"));
        hometowns.add(new Hometown("221", "تنکابن", "مازندران"));
        hometowns.add(new Hometown("582", "جویبار", "مازندران"));
        hometowns.add(new Hometown("483", "چالوس", "مازندران"));
        hometowns.add(new Hometown("625", "چمستان", "مازندران"));
        hometowns.add(new Hometown("576", "چهاردانگه", "مازندران"));
        hometowns.add(new Hometown("578", "دودانگه", "مازندران"));
        hometowns.add(new Hometown("227", "رامسر", "مازندران"));
        hometowns.add(new Hometown("208", "ساری", "مازندران"));
        hometowns.add(new Hometown("209", "ساری", "مازندران"));
        hometowns.add(new Hometown("225", "سوادکوه", "مازندران"));
        hometowns.add(new Hometown("577", "شیرگاه", "مازندران"));
        hometowns.add(new Hometown("712", "عباس آباد", "مازندران"));
        hometowns.add(new Hometown("215", "قائمشهر", "مازندران"));
        hometowns.add(new Hometown("216", "قائمشهر", "مازندران"));
        hometowns.add(new Hometown("626", "کجور", "مازندران"));
        hometowns.add(new Hometown("627", "کلاردشت", "مازندران"));
        hometowns.add(new Hometown("579", "گلوگاه", "مازندران"));
        hometowns.add(new Hometown("713", "میاندورود", "مازندران"));
        hometowns.add(new Hometown("499", "نکاء", "مازندران"));
        hometowns.add(new Hometown("222", "نور", "مازندران"));
        hometowns.add(new Hometown("219", "نوشهر", "مازندران"));
        hometowns.add(new Hometown("220", "نوشهر", "مازندران"));
        hometowns.add(new Hometown("500", "هراز و محمودآباد", "مازندران"));
        hometowns.add(new Hometown("501", "هراز و محمودآباد", "مازندران"));
        hometowns.add(new Hometown("623", "آزادشهر", "گلستان"));
        hometowns.add(new Hometown("497", "آق قلا", "گلستان"));
        hometowns.add(new Hometown("223", "بندرترکمن", "گلستان"));
        hometowns.add(new Hometown("689", "بندرگز", "گلستان"));
        hometowns.add(new Hometown("487", "رامیان", "گلستان"));
        hometowns.add(new Hometown("226", "علی آباد", "گلستان"));
        hometowns.add(new Hometown("224", "کردکوی", "گلستان"));
        hometowns.add(new Hometown("386", "کلاله", "گلستان"));
        hometowns.add(new Hometown("211", "گرگان", "گلستان"));
        hometowns.add(new Hometown("212", "گرگان", "گلستان"));
        hometowns.add(new Hometown("628", "گمیشان", "گلستان"));
        hometowns.add(new Hometown("202", "گنبد کاووس", "گلستان"));
        hometowns.add(new Hometown("203", "گنبد کاووس", "گلستان"));
        hometowns.add(new Hometown("531", "مراوه تپه", "گلستان"));
        hometowns.add(new Hometown("288", "مینودشت", "گلستان"));
        hometowns.add(new Hometown("261", "آستارا", "گیلان"));
        hometowns.add(new Hometown("273", "آستانه", "گیلان"));
        hometowns.add(new Hometown("630", "املش", "گیلان"));
        hometowns.add(new Hometown("264", "بندرانزلی", "گیلان"));
        hometowns.add(new Hometown("518", "خمام", "گیلان"));
        hometowns.add(new Hometown("631", "رحیم آباد", "گیلان"));
        hometowns.add(new Hometown("258", "رشت", "گیلان"));
        hometowns.add(new Hometown("259", "رشت", "گیلان"));
        hometowns.add(new Hometown("570", "رضوانشهر", "گیلان"));
        hometowns.add(new Hometown("265", "رودبار", "گیلان"));
        hometowns.add(new Hometown("268", "رودسر", "گیلان"));
        hometowns.add(new Hometown("269", "رودسر", "گیلان"));
        hometowns.add(new Hometown("653", "سنگر", "گیلان"));
        hometowns.add(new Hometown("517", "سیاهکل", "گیلان"));
        hometowns.add(new Hometown("569", "شفت", "گیلان"));
        hometowns.add(new Hometown("267", "صومعه سرا", "گیلان"));
        hometowns.add(new Hometown("262", "طالش", "گیلان"));
        hometowns.add(new Hometown("263", "طالش", "گیلان"));
        hometowns.add(new Hometown("593", "عمارلو", "گیلان"));
        hometowns.add(new Hometown("266", "فومن", "گیلان"));
        hometowns.add(new Hometown("693", "کوچصفهان", "گیلان"));
        hometowns.add(new Hometown("271", "لاهیجان", "گیلان"));
        hometowns.add(new Hometown("272", "لاهیجان", "گیلان"));
        hometowns.add(new Hometown("694", "لشت نشاء", "گیلان"));
        hometowns.add(new Hometown("270", "لنگرود", "گیلان"));
        hometowns.add(new Hometown("516", "ماسال و شاندرمن", "گیلان"));
        hometowns.add(new Hometown("333", "اسلام آباد", "کرمانشاه"));
        hometowns.add(new Hometown("334", "اسلام آباد", "کرمانشاه"));
        hometowns.add(new Hometown("691", "باینگان", "کرمانشاه"));
        hometowns.add(new Hometown("323", "پاوه", "کرمانشاه"));
        hometowns.add(new Hometown("322", "پاوه", "کرمانشاه"));
        hometowns.add(new Hometown("595", "ثلاث باباجانی", "کرمانشاه"));
        hometowns.add(new Hometown("395", "جوانرود", "کرمانشاه"));
        hometowns.add(new Hometown("641", "حمیل", "کرمانشاه"));
        hometowns.add(new Hometown("596", "روانسر", "کرمانشاه"));
        hometowns.add(new Hometown("336", "سرپل ذهاب", "کرمانشاه"));
        hometowns.add(new Hometown("335", "سنقر", "کرمانشاه"));
        hometowns.add(new Hometown("496", "صحنه", "کرمانشاه"));
        hometowns.add(new Hometown("337", "قصرشیرین", "کرمانشاه"));
        hometowns.add(new Hometown("324", "کرمانشاه", "کرمانشاه"));
        hometowns.add(new Hometown("325", "کرمانشاه", "کرمانشاه"));
        hometowns.add(new Hometown("394", "کرند", "کرمانشاه"));
        hometowns.add(new Hometown("330", "کنگاور", "کرمانشاه"));
        hometowns.add(new Hometown("332", "گیلانغرب", "کرمانشاه"));
        hometowns.add(new Hometown("331", "هرسین", "کرمانشاه"));
        hometowns.add(new Hometown("687", "باشت", "کهکیلویه و بویراحمد"));
        hometowns.add(new Hometown("422", "بویراحمد(یاسوج)", "کهکیلویه و بویراحمد"));
        hometowns.add(new Hometown("423", "بویراحمد(یاسوج)", "کهکیلویه و بویراحمد"));
        hometowns.add(new Hometown("599", "بهمنی", "کهکیلویه و بویراحمد"));
        hometowns.add(new Hometown("600", "چاروسا", "کهکیلویه و بویراحمد"));
        hometowns.add(new Hometown("688", "دروهان", "کهکیلویه و بویراحمد"));
        hometowns.add(new Hometown("424", "کهکیلویه(دهدشت)", "کهکیلویه و بویراحمد"));
        hometowns.add(new Hometown("425", "کهکیلویه(دهدشت)", "کهکیلویه و بویراحمد"));
        hometowns.add(new Hometown("426", "گچساران(دوگنبدان)", "کهکیلویه و بویراحمد"));
        hometowns.add(new Hometown("550", "لنده", "کهکیلویه و بویراحمد"));
        hometowns.add(new Hometown("697", "مارگون", "کهکیلویه و بویراحمد"));
        hometowns.add(new Hometown("384", "بانه", "کردستان"));
        hometowns.add(new Hometown("377", "بیجار", "کردستان"));
        hometowns.add(new Hometown("378", "بیجار", "کردستان"));
        hometowns.add(new Hometown("558", "دهگلان", "کردستان"));
        hometowns.add(new Hometown("385", "دیواندره", "کردستان"));
        hometowns.add(new Hometown("646", "سروآباد", "کردستان"));
        hometowns.add(new Hometown("375", "سقز", "کردستان"));
        hometowns.add(new Hometown("376", "سقز", "کردستان"));
        hometowns.add(new Hometown("372", "سنندج", "کردستان"));
        hometowns.add(new Hometown("373", "سنندج", "کردستان"));
        hometowns.add(new Hometown("379", "قروه", "کردستان"));
        hometowns.add(new Hometown("380", "قروه", "کردستان"));
        hometowns.add(new Hometown("383", "کامیاران", "کردستان"));
        hometowns.add(new Hometown("674", "کرانی", "کردستان"));
        hometowns.add(new Hometown("381", "مریوان", "کردستان"));
        hometowns.add(new Hometown("382", "مریوان", "کردستان"));
        hometowns.add(new Hometown("676", "نمشیر", "کردستان"));
        hometowns.add(new Hometown("722", "ارزونیه", "کرمان"));
        hometowns.add(new Hometown("542", "انار", "کرمان"));
        hometowns.add(new Hometown("312", "بافت", "کرمان"));
        hometowns.add(new Hometown("313", "بافت", "کرمان"));
        hometowns.add(new Hometown("317", "بردسیر", "کرمان"));
        hometowns.add(new Hometown("310", "بم", "کرمان"));
        hometowns.add(new Hometown("311", "بم", "کرمان"));
        hometowns.add(new Hometown("302", "جیرفت", "کرمان"));
        hometowns.add(new Hometown("303", "جیرفت", "کرمان"));
        hometowns.add(new Hometown("583", "رابر", "کرمان"));
        hometowns.add(new Hometown("321", "راور", "کرمان"));
        hometowns.add(new Hometown("382", "راین", "کرمان"));
        hometowns.add(new Hometown("304", "رفسنجان", "کرمان"));
        hometowns.add(new Hometown("305", "رفسنجان", "کرمان"));
        hometowns.add(new Hometown("305", "رفسنجان", "کرمان"));
        hometowns.add(new Hometown("536", "رودبار کهنوج", "کرمان"));
        hometowns.add(new Hometown("605", "ریگان", "کرمان"));
        hometowns.add(new Hometown("308", "زرند", "کرمان"));
        hometowns.add(new Hometown("309", "زرند", "کرمان"));
        hometowns.add(new Hometown("306", "سیرجان", "کرمان"));
        hometowns.add(new Hometown("307", "سیرجان", "کرمان"));
        hometowns.add(new Hometown("319", "شهداد", "کرمان"));
        hometowns.add(new Hometown("313", "شهربابک", "کرمان"));
        hometowns.add(new Hometown("314", "شهربابک", "کرمان"));
        hometowns.add(new Hometown("606", "عنبرآباد", "کرمان"));
        hometowns.add(new Hometown("320", "فهرج", "کرمان"));
        hometowns.add(new Hometown("698", "قلعه گنج", "کرمان"));
        hometowns.add(new Hometown("298", "کرمان", "کرمان"));
        hometowns.add(new Hometown("299", "کرمان", "کرمان"));
        hometowns.add(new Hometown("535", "کوهبنان", "کرمان"));
        hometowns.add(new Hometown("315", "کهنوج", "کرمان"));
        hometowns.add(new Hometown("316", "کهنوج", "کرمان"));
        hometowns.add(new Hometown("318", "گلباف", "کرمان"));
        hometowns.add(new Hometown("607", "ماهان", "کرمان"));
        hometowns.add(new Hometown("608", "منوجان", "کرمان"));
        hometowns.add(new Hometown("508", "آبیک", "قزوین"));
        hometowns.add(new Hometown("538", "آوج", "قزوین"));
        hometowns.add(new Hometown("728", "البرز", "قزوین"));
        hometowns.add(new Hometown("509", "بوئین زهرا", "قزوین"));
        hometowns.add(new Hometown("438", "تاکستان", "قزوین"));
        hometowns.add(new Hometown("439", "تاکستان", "قزوین"));
        hometowns.add(new Hometown("580", "رودبار الموت", "قزوین"));
        hometowns.add(new Hometown("590", "رودبار شهرستان", "قزوین"));
        hometowns.add(new Hometown("559", "ضیاءآباد", "قزوین"));
        hometowns.add(new Hometown("588", "طارم سفلی", "قزوین"));
        hometowns.add(new Hometown("431", "قزوین", "قزوین"));
        hometowns.add(new Hometown("432", "قزوین", "قزوین"));
        hometowns.add(new Hometown("037", "قم", "قم"));
        hometowns.add(new Hometown("038", "قم", "قم"));
        hometowns.add(new Hometown("702", "کهک", "قم"));
        hometowns.add(new Hometown("240", "آباده", "فارس"));
        hometowns.add(new Hometown("241", "آباده", "فارس"));
        hometowns.add(new Hometown("670", "آباده طشک", "فارس"));
        hometowns.add(new Hometown("648", "ارسنجان", "فارس"));
        hometowns.add(new Hometown("252", "استهبان", "فارس"));
        hometowns.add(new Hometown("678", "اشکنان", "فارس"));
        hometowns.add(new Hometown("253", "اقلید", "فارس"));
        hometowns.add(new Hometown("649", "اوز", "فارس"));
        hometowns.add(new Hometown("513", "بوانات", "فارس"));
        hometowns.add(new Hometown("546", "بیضا", "فارس"));
        hometowns.add(new Hometown("671", "جویم", "فارس"));
        hometowns.add(new Hometown("246", "جهرم", "فارس"));
        hometowns.add(new Hometown("247", "جهرم", "فارس"));
        hometowns.add(new Hometown("654", "حاجی آباد(زرین دشت)", "فارس"));
        hometowns.add(new Hometown("548", "خرامه", "فارس"));
        hometowns.add(new Hometown("547", "خشت و کمارج", "فارس"));
        hometowns.add(new Hometown("655", "خفر", "فارس"));
        hometowns.add(new Hometown("248", "داراب", "فارس"));
        hometowns.add(new Hometown("249", "داراب", "فارس"));
        hometowns.add(new Hometown("253", "سپیدان", "فارس"));
        hometowns.add(new Hometown("514", "سروستان", "فارس"));
        hometowns.add(new Hometown("665", "سعادت آباد", "فارس"));
        hometowns.add(new Hometown("673", "شیبکوه", "فارس"));
        hometowns.add(new Hometown("228", "شیراز", "فارس"));
        hometowns.add(new Hometown("229", "شیراز", "فارس"));
        hometowns.add(new Hometown("230", "شیراز", "فارس"));
        hometowns.add(new Hometown("679", "فراشبند", "فارس"));
        hometowns.add(new Hometown("256", "فسا", "فارس"));
        hometowns.add(new Hometown("257", "فسا", "فارس"));
        hometowns.add(new Hometown("244", "فیروزآباد", "فارس"));
        hometowns.add(new Hometown("245", "فیروزآباد", "فارس"));
        hometowns.add(new Hometown("681", "قنقری(خرم بید)", "فارس"));
        hometowns.add(new Hometown("723", "قیروکارزین", "فارس"));
        hometowns.add(new Hometown("236", "کازرون", "فارس"));
        hometowns.add(new Hometown("237", "کازرون", "فارس"));
        hometowns.add(new Hometown("683", "کوار", "فارس"));
        hometowns.add(new Hometown("656", "کراش", "فارس"));
        hometowns.add(new Hometown("250", "لارستان", "فارس"));
        hometowns.add(new Hometown("251", "لارستان", "فارس"));
        hometowns.add(new Hometown("515", "لامرد", "فارس"));
        hometowns.add(new Hometown("242", "مرودشت", "فارس"));
        hometowns.add(new Hometown("243", "مرودشت", "فارس"));
        hometowns.add(new Hometown("238", "ممسنی", "فارس"));
        hometowns.add(new Hometown("239", "ممسنی", "فارس"));
        hometowns.add(new Hometown("657", "مهر", "فارس"));
        hometowns.add(new Hometown("255", "نی ریز", "فارس"));
        hometowns.add(new Hometown("684", "ایوانکی", "سمنان"));
        hometowns.add(new Hometown("700", "بسطام", "سمنان"));
        hometowns.add(new Hometown("642", "بیارجمند", "سمنان"));
        hometowns.add(new Hometown("457", "دامغان", "سمنان"));
        hometowns.add(new Hometown("456", "سمنان", "سمنان"));
        hometowns.add(new Hometown("458", "شاهرود", "سمنان"));
        hometowns.add(new Hometown("459", "شاهرود", "سمنان"));
        hometowns.add(new Hometown("460", "گرمسار", "سمنان"));
        hometowns.add(new Hometown("530", "مهدیشهر", "سمنان"));
        hometowns.add(new Hometown("520", "میامی", "سمنان"));
        hometowns.add(new Hometown("358", "ایرانشهر", "سیستان و بلوچستان"));
        hometowns.add(new Hometown("359", "ایرانشهر", "سیستان و بلوچستان"));
        hometowns.add(new Hometown("682", "بزمان", "سیستان و بلوچستان"));
        hometowns.add(new Hometown("703", "بمپور", "سیستان و بلوچستان"));
        hometowns.add(new Hometown("364", "چابهار", "سیستان و بلوچستان"));
        hometowns.add(new Hometown("365", "چابهار", "سیستان و بلوچستان"));
        hometowns.add(new Hometown("371", "خاش", "سیستان و بلوچستان"));
        hometowns.add(new Hometown("701", "دشتیاری", "سیستان و بلوچستان"));
        hometowns.add(new Hometown("720", "راسک", "سیستان و بلوچستان"));
        hometowns.add(new Hometown("366", "زابل", "سیستان و بلوچستان"));
        hometowns.add(new Hometown("367", "زابل", "سیستان و بلوچستان"));
        hometowns.add(new Hometown("704", "زابلی", "سیستان و بلوچستان"));
        hometowns.add(new Hometown("361", "زاهدان", "سیستان و بلوچستان"));
        hometowns.add(new Hometown("362", "زاهدان", "سیستان و بلوچستان"));
        hometowns.add(new Hometown("369", "سراوان", "سیستان و بلوچستان"));
        hometowns.add(new Hometown("370", "سراوان", "سیستان و بلوچستان"));
        hometowns.add(new Hometown("635", "سرباز", "سیستان و بلوچستان"));
        hometowns.add(new Hometown("668", "سیب و سوران", "سیستان و بلوچستان"));
        hometowns.add(new Hometown("533", "شهرکی و ناروئی(زهک)", "سیستان و بلوچستان"));
        hometowns.add(new Hometown("705", "شیب آب", "سیستان و بلوچستان"));
        hometowns.add(new Hometown("699", "فنوج", "سیستان و بلوچستان"));
        hometowns.add(new Hometown("669", "قصرقند", "سیستان و بلوچستان"));
        hometowns.add(new Hometown("725", "کنارک", "سیستان و بلوچستان"));
        hometowns.add(new Hometown("597", "لاشار(اسپکه)", "سیستان و بلوچستان"));
        hometowns.add(new Hometown("611", "میرجاوه", "سیستان و بلوچستان"));
        hometowns.add(new Hometown("525", "نیک شهر", "سیستان و بلوچستان"));
        hometowns.add(new Hometown("181", "آبادان", "خوزستان"));
        hometowns.add(new Hometown("527", "آغاجاری", "خوزستان"));
        hometowns.add(new Hometown("585", "اروندکنار", "خوزستان"));
        hometowns.add(new Hometown("685", "امیدیه", "خوزستان"));
        hometowns.add(new Hometown("663", "اندیکا", "خوزستان"));
        hometowns.add(new Hometown("192", "اندیمشک", "خوزستان"));
        hometowns.add(new Hometown("193", "اندیمشک", "خوزستان"));
        hometowns.add(new Hometown("174", "اهواز", "خوزستان"));
        hometowns.add(new Hometown("175", "اهواز", "خوزستان"));
        hometowns.add(new Hometown("183", "ایذه", "خوزستان"));
        hometowns.add(new Hometown("184", "ایذه", "خوزستان"));
        hometowns.add(new Hometown("481", "باغ ملک", "خوزستان"));
        hometowns.add(new Hometown("706", "بندر امام خمینی", "خوزستان"));
        hometowns.add(new Hometown("194", "بندرماهشهر", "خوزستان"));
        hometowns.add(new Hometown("195", "بندرماهشهر", "خوزستان"));
        hometowns.add(new Hometown("185", "بهبهان", "خوزستان"));
        hometowns.add(new Hometown("186", "بهبهان", "خوزستان"));
        hometowns.add(new Hometown("182", "خرمشهر", "خوزستان"));
        hometowns.add(new Hometown("199", "دزفول", "خوزستان"));
        hometowns.add(new Hometown("200", "دزفول", "خوزستان"));
        hometowns.add(new Hometown("198", "دشت آزادگان", "خوزستان"));
        hometowns.add(new Hometown("662", "رامشیر", "خوزستان"));
        hometowns.add(new Hometown("190", "رامهرمز", "خوزستان"));
        hometowns.add(new Hometown("191", "رامهرمز", "خوزستان"));
        hometowns.add(new Hometown("692", "سردشت", "خوزستان"));
        hometowns.add(new Hometown("189", "شادگان", "خوزستان"));
        hometowns.add(new Hometown("707", "شاوور", "خوزستان"));
        hometowns.add(new Hometown("526", "شوش", "خوزستان"));
        hometowns.add(new Hometown("187", "شوشتر", "خوزستان"));
        hometowns.add(new Hometown("188", "شوشتر", "خوزستان"));
        hometowns.add(new Hometown("729", "گتوند", "خوزستان"));
        hometowns.add(new Hometown("730", "لالی", "خوزستان"));
        hometowns.add(new Hometown("196", "مسجدسلیمان", "خوزستان"));
        hometowns.add(new Hometown("197", "مسجدسلیمان", "خوزستان"));
        hometowns.add(new Hometown("661", "هندیجان", "خوزستان"));
        hometowns.add(new Hometown("680", "هویزه", "خوزستان"));
        hometowns.add(new Hometown("643", "احمدآباد", "خراسان رضوی"));
        hometowns.add(new Hometown("562", "بجستان", "خراسان رضوی"));
        hometowns.add(new Hometown("572", "بردسکن", "خراسان رضوی"));
        hometowns.add(new Hometown("074", "تایباد", "خراسان رضوی"));
        hometowns.add(new Hometown("644", "تخت جلگه", "خراسان رضوی"));
        hometowns.add(new Hometown("072", "تربت جام", "خراسان رضوی"));
        hometowns.add(new Hometown("073", "تربت جام", "خراسان رضوی"));
        hometowns.add(new Hometown("069", "تربت حیدریه", "خراسان رضوی"));
        hometowns.add(new Hometown("070", "تربت حیدریه", "خراسان رضوی"));
        hometowns.add(new Hometown("521", "جغتای", "خراسان رضوی"));
        hometowns.add(new Hometown("573", "جوین", "خراسان رضوی"));
        hometowns.add(new Hometown("522", "چناران", "خراسان رضوی"));
        hometowns.add(new Hometown("724", "خلیل آباد", "خراسان رضوی"));
        hometowns.add(new Hometown("076", "خواف", "خراسان رضوی"));
        hometowns.add(new Hometown("077", "درگز", "خراسان رضوی"));
        hometowns.add(new Hometown("650", "رشتخوار", "خراسان رضوی"));
        hometowns.add(new Hometown("574", "زبرخان", "خراسان رضوی"));
        hometowns.add(new Hometown("078", "سبزوار", "خراسان رضوی"));
        hometowns.add(new Hometown("079", "سبزوار", "خراسان رضوی"));
        hometowns.add(new Hometown("081", "سرخس", "خراسان رضوی"));
        hometowns.add(new Hometown("084", "فریمان", "خراسان رضوی"));
        hometowns.add(new Hometown("651", "فیض آباد", "خراسان رضوی"));
        hometowns.add(new Hometown("086", "قوچان", "خراسان رضوی"));
        hometowns.add(new Hometown("087", "قوچان", "خراسان رضوی"));
        hometowns.add(new Hometown("089", "کاشمر", "خراسان رضوی"));
        hometowns.add(new Hometown("090", "کاشمر", "خراسان رضوی"));
        hometowns.add(new Hometown("553", "کلات", "خراسان رضوی"));
        hometowns.add(new Hometown("091", "گناباد", "خراسان رضوی"));
        hometowns.add(new Hometown("092", "مشهد", "خراسان رضوی"));
        hometowns.add(new Hometown("093", "مشهد", "خراسان رضوی"));
        hometowns.add(new Hometown("094", "مشهد", "خراسان رضوی"));
        hometowns.add(new Hometown("097", "مشهد منطقه2", "خراسان رضوی"));
        hometowns.add(new Hometown("098", "مشهد منطقه3", "خراسان رضوی"));
        hometowns.add(new Hometown("096", "مشهد منطقه1", "خراسان رضوی"));
        hometowns.add(new Hometown("105", "نیشابور", "خراسان رضوی"));
        hometowns.add(new Hometown("106", "نیشابور", "خراسان رضوی"));
        hometowns.add(new Hometown("063", "اسفراین", "خراسان شمالی"));
        hometowns.add(new Hometown("067", "بجنورد", "خراسان شمالی"));
        hometowns.add(new Hometown("068", "بجنورد", "خراسان شمالی"));
        hometowns.add(new Hometown("075", "جاجرم", "خراسان شمالی"));
        hometowns.add(new Hometown("591", "رازوجرکلان", "خراسان شمالی"));
        hometowns.add(new Hometown("082", "شیروان", "خراسان شمالی"));
        hometowns.add(new Hometown("635", "فاروج", "خراسان شمالی"));
        hometowns.add(new Hometown("524", "مانه و سملقان", "خراسان شمالی"));
        hometowns.add(new Hometown("468", "اردل", "چهارمحال و بختیاری"));
        hometowns.add(new Hometown("465", "بروجن", "چهارمحال و بختیاری"));
        hometowns.add(new Hometown("461", "شهرکرد", "چهارمحال و بختیاری"));
        hometowns.add(new Hometown("462", "شهرکرد", "چهارمحال و بختیاری"));
        hometowns.add(new Hometown("467", "فارسان", "چهارمحال و بختیاری"));
        hometowns.add(new Hometown("632", "فلارد", "چهارمحال و بختیاری"));
        hometowns.add(new Hometown("555", "کوهرنگ", "چهارمحال و بختیاری"));
        hometowns.add(new Hometown("633", "کیار", "چهارمحال و بختیاری"));
        hometowns.add(new Hometown("629", "گندمان", "چهارمحال و بختیاری"));
        hometowns.add(new Hometown("466", "لردگان", "چهارمحال و بختیاری"));
        hometowns.add(new Hometown("696", "میانکوه", "چهارمحال و بختیاری"));
        hometowns.add(new Hometown("721", "بشرویه", "خراسان جنوبی"));
        hometowns.add(new Hometown("064", "بیرجند", "خراسان جنوبی"));
        hometowns.add(new Hometown("065", "بیرجند", "خراسان جنوبی"));
        hometowns.add(new Hometown("523", "درمیان", "خراسان جنوبی"));
        hometowns.add(new Hometown("652", "زیرکوه", "خراسان جنوبی"));
        hometowns.add(new Hometown("719", "سرایان", "خراسان جنوبی"));
        hometowns.add(new Hometown("716", "سربیشه", "خراسان جنوبی"));
        hometowns.add(new Hometown("085", "فردوس", "خراسان جنوبی"));
        hometowns.add(new Hometown("088", "قائنات", "خراسان جنوبی"));
        hometowns.add(new Hometown("563", "نهبندان", "خراسان جنوبی"));
        hometowns.add(new Hometown("529", "بندر دیلم", "بوشهر"));
        hometowns.add(new Hometown("353", "بندر گناوه", "بوشهر"));
        hometowns.add(new Hometown("349", "بوشهر", "بوشهر"));
        hometowns.add(new Hometown("350", "بوشهر", "بوشهر"));
        hometowns.add(new Hometown("355", "تنگستان", "بوشهر"));
        hometowns.add(new Hometown("609", "جم", "بوشهر"));
        hometowns.add(new Hometown("351", "دشتستان", "بوشهر"));
        hometowns.add(new Hometown("352", "دشتستان", "بوشهر"));
        hometowns.add(new Hometown("354", "دشتی", "بوشهر"));
        hometowns.add(new Hometown("732", "دلوار", "بوشهر"));
        hometowns.add(new Hometown("357", "دیر", "بوشهر"));
        hometowns.add(new Hometown("532", "سعد آباد", "بوشهر"));
        hometowns.add(new Hometown("610", "شبانکاره", "بوشهر"));
        hometowns.add(new Hometown("356", "کنگان", "بوشهر"));
        hometowns.add(new Hometown("556", "اسلامشهر", "تهران"));
        hometowns.add(new Hometown("658", "پاکدشت", "تهران"));
        hometowns.add(new Hometown("001", "تهران مرکزی", "تهران"));
        hometowns.add(new Hometown("002", "تهران مرکزی", "تهران"));
        hometowns.add(new Hometown("003", "تهران مرکزی", "تهران"));
        hometowns.add(new Hometown("004", "تهران مرکزی", "تهران"));
        hometowns.add(new Hometown("005", "تهران مرکزی", "تهران"));
        hometowns.add(new Hometown("006", "تهران مرکزی", "تهران"));
        hometowns.add(new Hometown("007", "تهران مرکزی", "تهران"));
        hometowns.add(new Hometown("008", "تهران مرکزی", "تهران"));
        hometowns.add(new Hometown("011", "تهران جنوب", "تهران"));
        hometowns.add(new Hometown("020", "تهران شرق", "تهران"));
        hometowns.add(new Hometown("025", "تهرانشمال", "تهران"));
        hometowns.add(new Hometown("015", "تهران غرب", "تهران"));
        hometowns.add(new Hometown("043", "دماوند", "تهران"));
        hometowns.add(new Hometown("666", "رباط کریم", "تهران"));
        hometowns.add(new Hometown("489", "ساوجبلاغ", "تهران"));
        hometowns.add(new Hometown("044", "شمیران", "تهران"));
        hometowns.add(new Hometown("045", "شمیران", "تهران"));
        hometowns.add(new Hometown("048", "شهرری", "تهران"));
        hometowns.add(new Hometown("049", "شهرری", "تهران"));
        hometowns.add(new Hometown("490", "شهریار", "تهران"));
        hometowns.add(new Hometown("491", "شهریار", "تهران"));
        hometowns.add(new Hometown("695", "طالقان", "تهران"));
        hometowns.add(new Hometown("659", "فیروزکوه", "تهران"));
        hometowns.add(new Hometown("031", "کرج", "تهران"));
        hometowns.add(new Hometown("032", "کرج", "تهران"));
        hometowns.add(new Hometown("664", "کهریزک", "تهران"));
        hometowns.add(new Hometown("717", "نظرآباد", "تهران"));
        hometowns.add(new Hometown("041", "ورامین", "تهران"));
        hometowns.add(new Hometown("042", "ورامین", "تهران"));
        hometowns.add(new Hometown("471", "امور خارجه", "امور خارجه"));
        hometowns.add(new Hometown("472", "امور خارجه", "امور خارجه"));
        hometowns.add(new Hometown("454", "آبدانان", "ایلام"));
        hometowns.add(new Hometown("581", "ارکوازی(ملکشاهی)", "ایلام"));
        hometowns.add(new Hometown("449", "ایلام", "ایلام"));
        hometowns.add(new Hometown("450", "ایلام", "ایلام"));
        hometowns.add(new Hometown("616", "ایوان", "ایلام"));
        hometowns.add(new Hometown("534", "بدره", "ایلام"));
        hometowns.add(new Hometown("455", "دره شهر", "ایلام"));
        hometowns.add(new Hometown("451", "دهلران", "ایلام"));
        hometowns.add(new Hometown("726", "زرین آباد", "ایلام"));
        hometowns.add(new Hometown("634", "شیروان لومار", "ایلام"));
        hometowns.add(new Hometown("453", "شیروان و چرداول", "ایلام"));
        hometowns.add(new Hometown("727", "موسیان", "ایلام"));
        hometowns.add(new Hometown("452", "مهران", "ایلام"));
        hometowns.add(new Hometown("145", "اردبیل", "اردبیل"));
        hometowns.add(new Hometown("146", "اردبیل", "اردبیل"));
        hometowns.add(new Hometown("731", "ارشق", "اردبیل"));
        hometowns.add(new Hometown("690", "انگوت", "اردبیل"));
        hometowns.add(new Hometown("601", "بیله سوار", "اردبیل"));
        hometowns.add(new Hometown("504", "پارس آباد", "اردبیل"));
        hometowns.add(new Hometown("163", "خلخال", "اردبیل"));
        hometowns.add(new Hometown("714", "خورش رستم", "اردبیل"));
        hometowns.add(new Hometown("715", "سرعین", "اردبیل"));
        hometowns.add(new Hometown("566", "سنجبد(کوثر)", "اردبیل"));
        hometowns.add(new Hometown("166", "مشکین شهر", "اردبیل"));
        hometowns.add(new Hometown("167", "مشکین شهر", "اردبیل"));
        hometowns.add(new Hometown("161", "مغان", "اردبیل"));
        hometowns.add(new Hometown("162", "مغان", "اردبیل"));
        hometowns.add(new Hometown("686", "نمین", "اردبیل"));
        hometowns.add(new Hometown("603", "نیر", "اردبیل"));
        hometowns.add(new Hometown("619", "آران و بیدگل", "اصفهان"));
        hometowns.add(new Hometown("118", "اردستان", "اصفهان"));
        hometowns.add(new Hometown("127", "اصفهان", "اصفهان"));
        hometowns.add(new Hometown("128", "اصفهان", "اصفهان"));
        hometowns.add(new Hometown("129", "اصفهان", "اصفهان"));
        hometowns.add(new Hometown("620", "باغ بهادران", "اصفهان"));
        hometowns.add(new Hometown("621", "بوئین و میاندشت", "اصفهان"));
        hometowns.add(new Hometown("549", "تیران و کرون", "اصفهان"));
        hometowns.add(new Hometown("564", "جرقویه", "اصفهان"));
        hometowns.add(new Hometown("575", "چادگان", "اصفهان"));
        hometowns.add(new Hometown("113", "خمینی شهر", "اصفهان"));
        hometowns.add(new Hometown("114", "خمینی شهر", "اصفهان"));
        hometowns.add(new Hometown("122", "خوانسار", "اصفهان"));
        hometowns.add(new Hometown("540", "خور و بیابانک", "اصفهان"));
        hometowns.add(new Hometown("660", "دولت آباد", "اصفهان"));
        hometowns.add(new Hometown("120", "سمیرم", "اصفهان"));
        hometowns.add(new Hometown("512", "سمیرم سفلی (دهاقان)", "اصفهان"));
        hometowns.add(new Hometown("510", "شاهین شهر", "اصفهان"));
        hometowns.add(new Hometown("511", "شاهین شهر", "اصفهان"));
        hometowns.add(new Hometown("119", "شهرضا", "اصفهان"));
        hometowns.add(new Hometown("115", "فریدن", "اصفهان"));
        hometowns.add(new Hometown("112", "فریدونشهر", "اصفهان"));
        hometowns.add(new Hometown("110", "فلاورجان", "اصفهان"));
        hometowns.add(new Hometown("111", "فلاورجان", "اصفهان"));
        hometowns.add(new Hometown("125", "کاشان", "اصفهان"));
        hometowns.add(new Hometown("126", "کاشان", "اصفهان"));
        hometowns.add(new Hometown("565", "کوهپایه", "اصفهان"));
        hometowns.add(new Hometown("121", "گلپایگان", "اصفهان"));
        hometowns.add(new Hometown("116", "لنجان(زرینشهر)", "اصفهان"));
        hometowns.add(new Hometown("117", "لنجان(زرینشهر)", "اصفهان"));
        hometowns.add(new Hometown("541", "مبارکه", "اصفهان"));
        hometowns.add(new Hometown("622", "میمه", "اصفهان"));
        hometowns.add(new Hometown("124", "نائین", "اصفهان"));
        hometowns.add(new Hometown("108", "نجف آباد", "اصفهان"));
        hometowns.add(new Hometown("109", "نجف آباد", "اصفهان"));
        hometowns.add(new Hometown("123", "نطنز", "اصفهان"));
        hometowns.add(new Hometown("428", "زنجان", "اصفهان"));
        hometowns.add(new Hometown("427", "زنجان", "اصفهان"));
        hometowns.add(new Hometown("507", "ملکان", "اصفهان"));
        hometowns.add(new Hometown("158", "مرند", "اصفهان"));
        hometowns.add(new Hometown("615", "ابهر", "اصفهان"));
        hometowns.add(new Hometown("615", "خرمدره", "اصفهان"));
        hometowns.add(new Hometown("152", "میانه", "اصفهان"));
        hometowns.add(new Hometown("153", "میانه", "اصفهان"));
    }
}