package dev.persiantools.usecases.collections;

import dev.persiantools.commons.*;

import java.util.*;

public class HometownCollection {

    private static HometownCollection instance;
    private Map<String, Hometown> hometowns;

    private HometownCollection() {
        hometowns = new HashMap<>();
    }

    public static HometownCollection getInstance() {
        if (instance == null) {
            synchronized (HometownCollection.class) {
                if (instance == null) {
                    instance = new HometownCollection();
                    instance.addHometowns();
                }
            }
        }
        return instance;
    }

    public Hometown find(String code) {
        if (hometowns.containsKey(code))
            return hometowns.get(code);
        return null;
    }

    private void addHometowns() {

        hometowns.put("169", new Hometown("آذرشهر", "آذربایجان شرقی"));
        hometowns.put("170", new Hometown("اسکو", "آذربایجان شرقی"));
        hometowns.put("149", new Hometown("اهر", "آذربایجان شرقی"));
        hometowns.put("150", new Hometown("اهر", "آذربایجان شرقی"));
        hometowns.put("171", new Hometown("بستان آباد", "آذربایجان شرقی"));
        hometowns.put("168", new Hometown("بناب", "آذربایجان شرقی"));
        hometowns.put("136", new Hometown("تبریز", "آذربایجان شرقی"));
        hometowns.put("137", new Hometown("تبریز", "آذربایجان شرقی"));
        hometowns.put("138", new Hometown("تبریز", "آذربایجان شرقی"));
        hometowns.put("545", new Hometown("ترکمانچای", "آذربایجان شرقی"));
        hometowns.put("505", new Hometown("جلفا", "آذربایجان شرقی"));
        hometowns.put("636", new Hometown("چاروایماق", "آذربایجان شرقی"));
        hometowns.put("164", new Hometown("سراب", "آذربایجان شرقی"));
        hometowns.put("165", new Hometown("سراب", "آذربایجان شرقی"));
        hometowns.put("172", new Hometown("شبستر", "آذربایجان شرقی"));
        hometowns.put("623", new Hometown("صوفیان", "آذربایجان شرقی"));
        hometowns.put("506", new Hometown("عجب شیر", "آذربایجان شرقی"));
        hometowns.put("519", new Hometown("کلیبر", "آذربایجان شرقی"));
        hometowns.put("154", new Hometown("مراغه", "آذربایجان شرقی"));
        hometowns.put("155", new Hometown("مراغه", "آذربایجان شرقی"));
        hometowns.put("567", new Hometown("ورزقان", "آذربایجان شرقی"));
        hometowns.put("173", new Hometown("هریس", "آذربایجان شرقی"));
        hometowns.put("159", new Hometown("هشترود", "آذربایجان شرقی"));
        hometowns.put("160", new Hometown("هشترود", "آذربایجان شرقی"));
        hometowns.put("604", new Hometown("هوراند", "آذربایجان شرقی"));
        hometowns.put("274", new Hometown("ارومیه", "آذربایجان غربی"));
        hometowns.put("275", new Hometown("ارومیه", "آذربایجان غربی"));
        hometowns.put("295", new Hometown("اشنویه", "آذربایجان غربی"));
        hometowns.put("637", new Hometown("انزل", "آذربایجان غربی"));
        hometowns.put("292", new Hometown("بوکان", "آذربایجان غربی"));
        hometowns.put("492", new Hometown("پلدشت", "آذربایجان غربی"));
        hometowns.put("289", new Hometown("پیرانشهر", "آذربایجان غربی"));
        hometowns.put("677", new Hometown("تخت سلیمان", "آذربایجان غربی"));
        hometowns.put("294", new Hometown("تکاب", "آذربایجان غربی"));
        hometowns.put("493", new Hometown("چایپاره", "آذربایجان غربی"));
        hometowns.put("279", new Hometown("خوی", "آذربایجان غربی"));
        hometowns.put("280", new Hometown("خوی", "آذربایجان غربی"));
        hometowns.put("288", new Hometown("سردشت", "آذربایجان غربی"));
        hometowns.put("284", new Hometown("سلماس", "آذربایجان غربی"));
        hometowns.put("285", new Hometown("سلماس", "آذربایجان غربی"));
        hometowns.put("638", new Hometown("سیلوانه", "آذربایجان غربی"));
        hometowns.put("291", new Hometown("سیه چشمه(چالدران)", "آذربایجان غربی"));
        hometowns.put("640", new Hometown("شوط", "آذربایجان غربی"));
        hometowns.put("293", new Hometown("شاهین دژ", "آذربایجان غربی"));
        hometowns.put("675", new Hometown("کشاورز", "آذربایجان غربی"));
        hometowns.put("282", new Hometown("ماکو", "آذربایجان غربی"));
        hometowns.put("283", new Hometown("ماکو", "آذربایجان غربی"));
        hometowns.put("286", new Hometown("مهاباد", "آذربایجان غربی"));
        hometowns.put("287", new Hometown("مهاباد", "آذربایجان غربی"));
        hometowns.put("296", new Hometown("میاندوآب", "آذربایجان غربی"));
        hometowns.put("297", new Hometown("میاندوآب", "آذربایجان غربی"));
        hometowns.put("290", new Hometown("نقده", "آذربایجان غربی"));
        hometowns.put("400", new Hometown("اسدآباد", "همدان"));
        hometowns.put("401", new Hometown("اسدآباد", "همدان"));
        hometowns.put("404", new Hometown("بهار", "همدان"));
        hometowns.put("405", new Hometown("بهار", "همدان"));
        hometowns.put("397", new Hometown("تویسرکان", "همدان"));
        hometowns.put("398", new Hometown("رزن", "همدان"));
        hometowns.put("399", new Hometown("رزن", "همدان"));
        hometowns.put("647", new Hometown("شراء و پیشخوار", "همدان"));
        hometowns.put("502", new Hometown("فامنین", "همدان"));
        hometowns.put("584", new Hometown("قلقل رود", "همدان"));
        hometowns.put("402", new Hometown("کبودرآهنگ", "همدان"));
        hometowns.put("403", new Hometown("کبودرآهنگ", "همدان"));
        hometowns.put("392", new Hometown("ملایر", "همدان"));
        hometowns.put("393", new Hometown("ملایر", "همدان"));
        hometowns.put("395", new Hometown("نهاوند", "همدان"));
        hometowns.put("396", new Hometown("نهاوند", "همدان"));
        hometowns.put("386", new Hometown("همدان", "همدان"));
        hometowns.put("387", new Hometown("همدان", "همدان"));
        hometowns.put("503", new Hometown("ابرکوه", "یزد"));
        hometowns.put("444", new Hometown("اردکان", "یزد"));
        hometowns.put("551", new Hometown("اشکذر", "یزد"));
        hometowns.put("447", new Hometown("بافق", "یزد"));
        hometowns.put("561", new Hometown("بهاباد", "یزد"));
        hometowns.put("445", new Hometown("تفت", "یزد"));
        hometowns.put("718", new Hometown("دستگردان", "یزد"));
        hometowns.put("083", new Hometown("طبس", "یزد"));
        hometowns.put("446", new Hometown("مهریز", "یزد"));
        hometowns.put("448", new Hometown("میبد", "یزد"));
        hometowns.put("552", new Hometown("نیر", "یزد"));
        hometowns.put("543", new Hometown("هرات و مروست", "یزد"));
        hometowns.put("442", new Hometown("یزد", "یزد"));
        hometowns.put("443", new Hometown("یزد", "یزد"));
        hometowns.put("051", new Hometown("آشتیان", "مرکزی"));
        hometowns.put("052", new Hometown("اراک", "مرکزی"));
        hometowns.put("053", new Hometown("اراک", "مرکزی"));
        hometowns.put("058", new Hometown("تفرش", "مرکزی"));
        hometowns.put("055", new Hometown("خمین", "مرکزی"));
        hometowns.put("617", new Hometown("خنداب", "مرکزی"));
        hometowns.put("057", new Hometown("دلیجان", "مرکزی"));
        hometowns.put("618", new Hometown("زرند مرکزی", "مرکزی"));
        hometowns.put("059", new Hometown("ساوه", "مرکزی"));
        hometowns.put("060", new Hometown("ساوه", "مرکزی"));
        hometowns.put("061", new Hometown("سربند", "مرکزی"));
        hometowns.put("062", new Hometown("سربند", "مرکزی"));
        hometowns.put("544", new Hometown("فراهان", "مرکزی"));
        hometowns.put("056", new Hometown("محلات", "مرکزی"));
        hometowns.put("571", new Hometown("وفس", "مرکزی"));
        hometowns.put("593", new Hometown("هندودر", "مرکزی"));
        hometowns.put("667", new Hometown("ابوموسی", "هرمزگان"));
        hometowns.put("348", new Hometown("بستک", "هرمزگان"));
        hometowns.put("586", new Hometown("بشاگرد", "هرمزگان"));
        hometowns.put("338", new Hometown("بندرعباس", "هرمزگان"));
        hometowns.put("339", new Hometown("بندرعباس", "هرمزگان"));
        hometowns.put("343", new Hometown("بندرلنگه", "هرمزگان"));
        hometowns.put("344", new Hometown("بندرلنگه", "هرمزگان"));
        hometowns.put("346", new Hometown("جاسک", "هرمزگان"));
        hometowns.put("337", new Hometown("حاجی آباد", "هرمزگان"));
        hometowns.put("554", new Hometown("خمیر", "هرمزگان"));
        hometowns.put("469", new Hometown("رودان", "هرمزگان"));
        hometowns.put("537", new Hometown("فین", "هرمزگان"));
        hometowns.put("345", new Hometown("قشم", "هرمزگان"));
        hometowns.put("470", new Hometown("گاوبندی", "هرمزگان"));
        hometowns.put("341", new Hometown("میناب", "هرمزگان"));
        hometowns.put("342", new Hometown("میناب", "هرمزگان"));
        hometowns.put("483", new Hometown("ازنا", "لرستان"));
        hometowns.put("484", new Hometown("ازنا", "لرستان"));
        hometowns.put("557", new Hometown("اشترینان", "لرستان"));
        hometowns.put("418", new Hometown("الشتر", "لرستان"));
        hometowns.put("416", new Hometown("الیگودرز", "لرستان"));
        hometowns.put("417", new Hometown("الیگودرز", "لرستان"));
        hometowns.put("412", new Hometown("بروجرد", "لرستان"));
        hometowns.put("413", new Hometown("بروجرد", "لرستان"));
        hometowns.put("592", new Hometown("پاپی", "لرستان"));
        hometowns.put("612", new Hometown("چغلوندی", "لرستان"));
        hometowns.put("613", new Hometown("چگنی", "لرستان"));
        hometowns.put("406", new Hometown("خرم آباد", "لرستان"));
        hometowns.put("407", new Hometown("خرم آباد", "لرستان"));
        hometowns.put("421", new Hometown("دورود", "لرستان"));
        hometowns.put("598", new Hometown("رومشکان", "لرستان"));
        hometowns.put("419", new Hometown("کوهدشت", "لرستان"));
        hometowns.put("385", new Hometown("ملاوی(پلدختر)", "لرستان"));
        hometowns.put("420", new Hometown("نورآباد(دلفان)", "لرستان"));
        hometowns.put("528", new Hometown("ویسیان", "لرستان"));
        hometowns.put("213", new Hometown("آمل", "مازندران"));
        hometowns.put("214", new Hometown("آمل", "مازندران"));
        hometowns.put("205", new Hometown("بابل", "مازندران"));
        hometowns.put("206", new Hometown("بابل", "مازندران"));
        hometowns.put("498", new Hometown("بابل", "مازندران"));
        hometowns.put("568", new Hometown("بندپی", "مازندران"));
        hometowns.put("711", new Hometown("بندپی شرقی", "مازندران"));
        hometowns.put("217", new Hometown("بهشهر", "مازندران"));
        hometowns.put("218", new Hometown("بهشهر", "مازندران"));
        hometowns.put("221", new Hometown("تنکابن", "مازندران"));
        hometowns.put("582", new Hometown("جویبار", "مازندران"));
        hometowns.put("483", new Hometown("چالوس", "مازندران"));
        hometowns.put("625", new Hometown("چمستان", "مازندران"));
        hometowns.put("576", new Hometown("چهاردانگه", "مازندران"));
        hometowns.put("578", new Hometown("دودانگه", "مازندران"));
        hometowns.put("227", new Hometown("رامسر", "مازندران"));
        hometowns.put("208", new Hometown("ساری", "مازندران"));
        hometowns.put("209", new Hometown("ساری", "مازندران"));
        hometowns.put("225", new Hometown("سوادکوه", "مازندران"));
        hometowns.put("577", new Hometown("شیرگاه", "مازندران"));
        hometowns.put("712", new Hometown("عباس آباد", "مازندران"));
        hometowns.put("215", new Hometown("قائمشهر", "مازندران"));
        hometowns.put("216", new Hometown("قائمشهر", "مازندران"));
        hometowns.put("626", new Hometown("کجور", "مازندران"));
        hometowns.put("627", new Hometown("کلاردشت", "مازندران"));
        hometowns.put("579", new Hometown("گلوگاه", "مازندران"));
        hometowns.put("713", new Hometown("میاندورود", "مازندران"));
        hometowns.put("499", new Hometown("نکاء", "مازندران"));
        hometowns.put("222", new Hometown("نور", "مازندران"));
        hometowns.put("219", new Hometown("نوشهر", "مازندران"));
        hometowns.put("220", new Hometown("نوشهر", "مازندران"));
        hometowns.put("500", new Hometown("هراز و محمودآباد", "مازندران"));
        hometowns.put("501", new Hometown("هراز و محمودآباد", "مازندران"));
        hometowns.put("623", new Hometown("آزادشهر", "گلستان"));
        hometowns.put("497", new Hometown("آق قلا", "گلستان"));
        hometowns.put("223", new Hometown("بندرترکمن", "گلستان"));
        hometowns.put("689", new Hometown("بندرگز", "گلستان"));
        hometowns.put("487", new Hometown("رامیان", "گلستان"));
        hometowns.put("226", new Hometown("علی آباد", "گلستان"));
        hometowns.put("224", new Hometown("کردکوی", "گلستان"));
        hometowns.put("386", new Hometown("کلاله", "گلستان"));
        hometowns.put("211", new Hometown("گرگان", "گلستان"));
        hometowns.put("212", new Hometown("گرگان", "گلستان"));
        hometowns.put("628", new Hometown("گمیشان", "گلستان"));
        hometowns.put("202", new Hometown("گنبد کاووس", "گلستان"));
        hometowns.put("203", new Hometown("گنبد کاووس", "گلستان"));
        hometowns.put("531", new Hometown("مراوه تپه", "گلستان"));
        hometowns.put("288", new Hometown("مینودشت", "گلستان"));
        hometowns.put("261", new Hometown("آستارا", "گیلان"));
        hometowns.put("273", new Hometown("آستانه", "گیلان"));
        hometowns.put("630", new Hometown("املش", "گیلان"));
        hometowns.put("264", new Hometown("بندرانزلی", "گیلان"));
        hometowns.put("518", new Hometown("خمام", "گیلان"));
        hometowns.put("631", new Hometown("رحیم آباد", "گیلان"));
        hometowns.put("258", new Hometown("رشت", "گیلان"));
        hometowns.put("259", new Hometown("رشت", "گیلان"));
        hometowns.put("570", new Hometown("رضوانشهر", "گیلان"));
        hometowns.put("265", new Hometown("رودبار", "گیلان"));
        hometowns.put("268", new Hometown("رودسر", "گیلان"));
        hometowns.put("269", new Hometown("رودسر", "گیلان"));
        hometowns.put("653", new Hometown("سنگر", "گیلان"));
        hometowns.put("517", new Hometown("سیاهکل", "گیلان"));
        hometowns.put("569", new Hometown("شفت", "گیلان"));
        hometowns.put("267", new Hometown("صومعه سرا", "گیلان"));
        hometowns.put("262", new Hometown("طالش", "گیلان"));
        hometowns.put("263", new Hometown("طالش", "گیلان"));
        hometowns.put("593", new Hometown("عمارلو", "گیلان"));
        hometowns.put("266", new Hometown("فومن", "گیلان"));
        hometowns.put("693", new Hometown("کوچصفهان", "گیلان"));
        hometowns.put("271", new Hometown("لاهیجان", "گیلان"));
        hometowns.put("272", new Hometown("لاهیجان", "گیلان"));
        hometowns.put("694", new Hometown("لشت نشاء", "گیلان"));
        hometowns.put("270", new Hometown("لنگرود", "گیلان"));
        hometowns.put("516", new Hometown("ماسال و شاندرمن", "گیلان"));
        hometowns.put("333", new Hometown("اسلام آباد", "کرمانشاه"));
        hometowns.put("334", new Hometown("اسلام آباد", "کرمانشاه"));
        hometowns.put("691", new Hometown("باینگان", "کرمانشاه"));
        hometowns.put("323", new Hometown("پاوه", "کرمانشاه"));
        hometowns.put("322", new Hometown("پاوه", "کرمانشاه"));
        hometowns.put("595", new Hometown("ثلاث باباجانی", "کرمانشاه"));
        hometowns.put("395", new Hometown("جوانرود", "کرمانشاه"));
        hometowns.put("641", new Hometown("حمیل", "کرمانشاه"));
        hometowns.put("596", new Hometown("روانسر", "کرمانشاه"));
        hometowns.put("336", new Hometown("سرپل ذهاب", "کرمانشاه"));
        hometowns.put("335", new Hometown("سنقر", "کرمانشاه"));
        hometowns.put("496", new Hometown("صحنه", "کرمانشاه"));
        hometowns.put("337", new Hometown("قصرشیرین", "کرمانشاه"));
        hometowns.put("324", new Hometown("کرمانشاه", "کرمانشاه"));
        hometowns.put("325", new Hometown("کرمانشاه", "کرمانشاه"));
        hometowns.put("394", new Hometown("کرند", "کرمانشاه"));
        hometowns.put("330", new Hometown("کنگاور", "کرمانشاه"));
        hometowns.put("332", new Hometown("گیلانغرب", "کرمانشاه"));
        hometowns.put("331", new Hometown("هرسین", "کرمانشاه"));
        hometowns.put("687", new Hometown("باشت", "کهکیلویه و بویراحمد"));
        hometowns.put("422", new Hometown("بویراحمد(یاسوج)", "کهکیلویه و بویراحمد"));
        hometowns.put("423", new Hometown("بویراحمد(یاسوج)", "کهکیلویه و بویراحمد"));
        hometowns.put("599", new Hometown("بهمنی", "کهکیلویه و بویراحمد"));
        hometowns.put("600", new Hometown("چاروسا", "کهکیلویه و بویراحمد"));
        hometowns.put("688", new Hometown("دروهان", "کهکیلویه و بویراحمد"));
        hometowns.put("424", new Hometown("کهکیلویه(دهدشت)", "کهکیلویه و بویراحمد"));
        hometowns.put("425", new Hometown("کهکیلویه(دهدشت)", "کهکیلویه و بویراحمد"));
        hometowns.put("426", new Hometown("گچساران(دوگنبدان)", "کهکیلویه و بویراحمد"));
        hometowns.put("550", new Hometown("لنده", "کهکیلویه و بویراحمد"));
        hometowns.put("697", new Hometown("مارگون", "کهکیلویه و بویراحمد"));
        hometowns.put("384", new Hometown("بانه", "کردستان"));
        hometowns.put("377", new Hometown("بیجار", "کردستان"));
        hometowns.put("378", new Hometown("بیجار", "کردستان"));
        hometowns.put("558", new Hometown("دهگلان", "کردستان"));
        hometowns.put("385", new Hometown("دیواندره", "کردستان"));
        hometowns.put("646", new Hometown("سروآباد", "کردستان"));
        hometowns.put("375", new Hometown("سقز", "کردستان"));
        hometowns.put("376", new Hometown("سقز", "کردستان"));
        hometowns.put("372", new Hometown("سنندج", "کردستان"));
        hometowns.put("373", new Hometown("سنندج", "کردستان"));
        hometowns.put("379", new Hometown("قروه", "کردستان"));
        hometowns.put("380", new Hometown("قروه", "کردستان"));
        hometowns.put("383", new Hometown("کامیاران", "کردستان"));
        hometowns.put("674", new Hometown("کرانی", "کردستان"));
        hometowns.put("381", new Hometown("مریوان", "کردستان"));
        hometowns.put("382", new Hometown("مریوان", "کردستان"));
        hometowns.put("676", new Hometown("نمشیر", "کردستان"));
        hometowns.put("722", new Hometown("ارزونیه", "کرمان"));
        hometowns.put("542", new Hometown("انار", "کرمان"));
        hometowns.put("312", new Hometown("بافت", "کرمان"));
        hometowns.put("313", new Hometown("بافت", "کرمان"));
        hometowns.put("317", new Hometown("بردسیر", "کرمان"));
        hometowns.put("310", new Hometown("بم", "کرمان"));
        hometowns.put("311", new Hometown("بم", "کرمان"));
        hometowns.put("302", new Hometown("جیرفت", "کرمان"));
        hometowns.put("303", new Hometown("جیرفت", "کرمان"));
        hometowns.put("583", new Hometown("رابر", "کرمان"));
        hometowns.put("321", new Hometown("راور", "کرمان"));
        hometowns.put("382", new Hometown("راین", "کرمان"));
        hometowns.put("304", new Hometown("رفسنجان", "کرمان"));
        hometowns.put("305", new Hometown("رفسنجان", "کرمان"));
        hometowns.put("305", new Hometown("رفسنجان", "کرمان"));
        hometowns.put("536", new Hometown("رودبار کهنوج", "کرمان"));
        hometowns.put("605", new Hometown("ریگان", "کرمان"));
        hometowns.put("308", new Hometown("زرند", "کرمان"));
        hometowns.put("309", new Hometown("زرند", "کرمان"));
        hometowns.put("306", new Hometown("سیرجان", "کرمان"));
        hometowns.put("307", new Hometown("سیرجان", "کرمان"));
        hometowns.put("319", new Hometown("شهداد", "کرمان"));
        hometowns.put("313", new Hometown("شهربابک", "کرمان"));
        hometowns.put("314", new Hometown("شهربابک", "کرمان"));
        hometowns.put("606", new Hometown("عنبرآباد", "کرمان"));
        hometowns.put("320", new Hometown("فهرج", "کرمان"));
        hometowns.put("698", new Hometown("قلعه گنج", "کرمان"));
        hometowns.put("298", new Hometown("کرمان", "کرمان"));
        hometowns.put("299", new Hometown("کرمان", "کرمان"));
        hometowns.put("535", new Hometown("کوهبنان", "کرمان"));
        hometowns.put("315", new Hometown("کهنوج", "کرمان"));
        hometowns.put("316", new Hometown("کهنوج", "کرمان"));
        hometowns.put("318", new Hometown("گلباف", "کرمان"));
        hometowns.put("607", new Hometown("ماهان", "کرمان"));
        hometowns.put("608", new Hometown("منوجان", "کرمان"));
        hometowns.put("508", new Hometown("آبیک", "قزوین"));
        hometowns.put("538", new Hometown("آوج", "قزوین"));
        hometowns.put("728", new Hometown("البرز", "قزوین"));
        hometowns.put("509", new Hometown("بوئین زهرا", "قزوین"));
        hometowns.put("438", new Hometown("تاکستان", "قزوین"));
        hometowns.put("439", new Hometown("تاکستان", "قزوین"));
        hometowns.put("580", new Hometown("رودبار الموت", "قزوین"));
        hometowns.put("590", new Hometown("رودبار شهرستان", "قزوین"));
        hometowns.put("559", new Hometown("ضیاءآباد", "قزوین"));
        hometowns.put("588", new Hometown("طارم سفلی", "قزوین"));
        hometowns.put("431", new Hometown("قزوین", "قزوین"));
        hometowns.put("432", new Hometown("قزوین", "قزوین"));
        hometowns.put("037", new Hometown("قم", "قم"));
        hometowns.put("038", new Hometown("قم", "قم"));
        hometowns.put("702", new Hometown("کهک", "قم"));
        hometowns.put("240", new Hometown("آباده", "فارس"));
        hometowns.put("241", new Hometown("آباده", "فارس"));
        hometowns.put("670", new Hometown("آباده طشک", "فارس"));
        hometowns.put("648", new Hometown("ارسنجان", "فارس"));
        hometowns.put("252", new Hometown("استهبان", "فارس"));
        hometowns.put("678", new Hometown("اشکنان", "فارس"));
        hometowns.put("253", new Hometown("اقلید", "فارس"));
        hometowns.put("649", new Hometown("اوز", "فارس"));
        hometowns.put("513", new Hometown("بوانات", "فارس"));
        hometowns.put("546", new Hometown("بیضا", "فارس"));
        hometowns.put("671", new Hometown("جویم", "فارس"));
        hometowns.put("246", new Hometown("جهرم", "فارس"));
        hometowns.put("247", new Hometown("جهرم", "فارس"));
        hometowns.put("654", new Hometown("حاجی آباد(زرین دشت)", "فارس"));
        hometowns.put("548", new Hometown("خرامه", "فارس"));
        hometowns.put("547", new Hometown("خشت و کمارج", "فارس"));
        hometowns.put("655", new Hometown("خفر", "فارس"));
        hometowns.put("248", new Hometown("داراب", "فارس"));
        hometowns.put("249", new Hometown("داراب", "فارس"));
        hometowns.put("253", new Hometown("سپیدان", "فارس"));
        hometowns.put("514", new Hometown("سروستان", "فارس"));
        hometowns.put("665", new Hometown("سعادت آباد", "فارس"));
        hometowns.put("673", new Hometown("شیبکوه", "فارس"));
        hometowns.put("228", new Hometown("شیراز", "فارس"));
        hometowns.put("229", new Hometown("شیراز", "فارس"));
        hometowns.put("230", new Hometown("شیراز", "فارس"));
        hometowns.put("679", new Hometown("فراشبند", "فارس"));
        hometowns.put("256", new Hometown("فسا", "فارس"));
        hometowns.put("257", new Hometown("فسا", "فارس"));
        hometowns.put("244", new Hometown("فیروزآباد", "فارس"));
        hometowns.put("245", new Hometown("فیروزآباد", "فارس"));
        hometowns.put("681", new Hometown("قنقری(خرم بید)", "فارس"));
        hometowns.put("723", new Hometown("قیروکارزین", "فارس"));
        hometowns.put("236", new Hometown("کازرون", "فارس"));
        hometowns.put("237", new Hometown("کازرون", "فارس"));
        hometowns.put("683", new Hometown("کوار", "فارس"));
        hometowns.put("656", new Hometown("کراش", "فارس"));
        hometowns.put("250", new Hometown("لارستان", "فارس"));
        hometowns.put("251", new Hometown("لارستان", "فارس"));
        hometowns.put("515", new Hometown("لامرد", "فارس"));
        hometowns.put("242", new Hometown("مرودشت", "فارس"));
        hometowns.put("243", new Hometown("مرودشت", "فارس"));
        hometowns.put("238", new Hometown("ممسنی", "فارس"));
        hometowns.put("239", new Hometown("ممسنی", "فارس"));
        hometowns.put("657", new Hometown("مهر", "فارس"));
        hometowns.put("255", new Hometown("نی ریز", "فارس"));
        hometowns.put("684", new Hometown("ایوانکی", "سمنان"));
        hometowns.put("700", new Hometown("بسطام", "سمنان"));
        hometowns.put("642", new Hometown("بیارجمند", "سمنان"));
        hometowns.put("457", new Hometown("دامغان", "سمنان"));
        hometowns.put("456", new Hometown("سمنان", "سمنان"));
        hometowns.put("458", new Hometown("شاهرود", "سمنان"));
        hometowns.put("459", new Hometown("شاهرود", "سمنان"));
        hometowns.put("460", new Hometown("گرمسار", "سمنان"));
        hometowns.put("530", new Hometown("مهدیشهر", "سمنان"));
        hometowns.put("520", new Hometown("میامی", "سمنان"));
        hometowns.put("358", new Hometown("ایرانشهر", "سیستان و بلوچستان"));
        hometowns.put("359", new Hometown("ایرانشهر", "سیستان و بلوچستان"));
        hometowns.put("682", new Hometown("بزمان", "سیستان و بلوچستان"));
        hometowns.put("703", new Hometown("بمپور", "سیستان و بلوچستان"));
        hometowns.put("364", new Hometown("چابهار", "سیستان و بلوچستان"));
        hometowns.put("365", new Hometown("چابهار", "سیستان و بلوچستان"));
        hometowns.put("371", new Hometown("خاش", "سیستان و بلوچستان"));
        hometowns.put("701", new Hometown("دشتیاری", "سیستان و بلوچستان"));
        hometowns.put("720", new Hometown("راسک", "سیستان و بلوچستان"));
        hometowns.put("366", new Hometown("زابل", "سیستان و بلوچستان"));
        hometowns.put("367", new Hometown("زابل", "سیستان و بلوچستان"));
        hometowns.put("704", new Hometown("زابلی", "سیستان و بلوچستان"));
        hometowns.put("361", new Hometown("زاهدان", "سیستان و بلوچستان"));
        hometowns.put("362", new Hometown("زاهدان", "سیستان و بلوچستان"));
        hometowns.put("369", new Hometown("سراوان", "سیستان و بلوچستان"));
        hometowns.put("370", new Hometown("سراوان", "سیستان و بلوچستان"));
        hometowns.put("635", new Hometown("سرباز", "سیستان و بلوچستان"));
        hometowns.put("668", new Hometown("سیب و سوران", "سیستان و بلوچستان"));
        hometowns.put("533", new Hometown("شهرکی و ناروئی(زهک)", "سیستان و بلوچستان"));
        hometowns.put("705", new Hometown("شیب آب", "سیستان و بلوچستان"));
        hometowns.put("699", new Hometown("فنوج", "سیستان و بلوچستان"));
        hometowns.put("669", new Hometown("قصرقند", "سیستان و بلوچستان"));
        hometowns.put("725", new Hometown("کنارک", "سیستان و بلوچستان"));
        hometowns.put("597", new Hometown("لاشار(اسپکه)", "سیستان و بلوچستان"));
        hometowns.put("611", new Hometown("میرجاوه", "سیستان و بلوچستان"));
        hometowns.put("525", new Hometown("نیک شهر", "سیستان و بلوچستان"));
        hometowns.put("181", new Hometown("آبادان", "خوزستان"));
        hometowns.put("527", new Hometown("آغاجاری", "خوزستان"));
        hometowns.put("585", new Hometown("اروندکنار", "خوزستان"));
        hometowns.put("685", new Hometown("امیدیه", "خوزستان"));
        hometowns.put("663", new Hometown("اندیکا", "خوزستان"));
        hometowns.put("192", new Hometown("اندیمشک", "خوزستان"));
        hometowns.put("193", new Hometown("اندیمشک", "خوزستان"));
        hometowns.put("174", new Hometown("اهواز", "خوزستان"));
        hometowns.put("175", new Hometown("اهواز", "خوزستان"));
        hometowns.put("183", new Hometown("ایذه", "خوزستان"));
        hometowns.put("184", new Hometown("ایذه", "خوزستان"));
        hometowns.put("481", new Hometown("باغ ملک", "خوزستان"));
        hometowns.put("706", new Hometown("بندر امام خمینی", "خوزستان"));
        hometowns.put("194", new Hometown("بندرماهشهر", "خوزستان"));
        hometowns.put("195", new Hometown("بندرماهشهر", "خوزستان"));
        hometowns.put("185", new Hometown("بهبهان", "خوزستان"));
        hometowns.put("186", new Hometown("بهبهان", "خوزستان"));
        hometowns.put("182", new Hometown("خرمشهر", "خوزستان"));
        hometowns.put("199", new Hometown("دزفول", "خوزستان"));
        hometowns.put("200", new Hometown("دزفول", "خوزستان"));
        hometowns.put("198", new Hometown("دشت آزادگان", "خوزستان"));
        hometowns.put("662", new Hometown("رامشیر", "خوزستان"));
        hometowns.put("190", new Hometown("رامهرمز", "خوزستان"));
        hometowns.put("191", new Hometown("رامهرمز", "خوزستان"));
        hometowns.put("692", new Hometown("سردشت", "خوزستان"));
        hometowns.put("189", new Hometown("شادگان", "خوزستان"));
        hometowns.put("707", new Hometown("شاوور", "خوزستان"));
        hometowns.put("526", new Hometown("شوش", "خوزستان"));
        hometowns.put("187", new Hometown("شوشتر", "خوزستان"));
        hometowns.put("188", new Hometown("شوشتر", "خوزستان"));
        hometowns.put("729", new Hometown("گتوند", "خوزستان"));
        hometowns.put("730", new Hometown("لالی", "خوزستان"));
        hometowns.put("196", new Hometown("مسجدسلیمان", "خوزستان"));
        hometowns.put("197", new Hometown("مسجدسلیمان", "خوزستان"));
        hometowns.put("661", new Hometown("هندیجان", "خوزستان"));
        hometowns.put("680", new Hometown("هویزه", "خوزستان"));
        hometowns.put("643", new Hometown("احمدآباد", "خراسان رضوی"));
        hometowns.put("562", new Hometown("بجستان", "خراسان رضوی"));
        hometowns.put("572", new Hometown("بردسکن", "خراسان رضوی"));
        hometowns.put("074", new Hometown("تایباد", "خراسان رضوی"));
        hometowns.put("644", new Hometown("تخت جلگه", "خراسان رضوی"));
        hometowns.put("072", new Hometown("تربت جام", "خراسان رضوی"));
        hometowns.put("073", new Hometown("تربت جام", "خراسان رضوی"));
        hometowns.put("069", new Hometown("تربت حیدریه", "خراسان رضوی"));
        hometowns.put("070", new Hometown("تربت حیدریه", "خراسان رضوی"));
        hometowns.put("521", new Hometown("جغتای", "خراسان رضوی"));
        hometowns.put("573", new Hometown("جوین", "خراسان رضوی"));
        hometowns.put("522", new Hometown("چناران", "خراسان رضوی"));
        hometowns.put("724", new Hometown("خلیل آباد", "خراسان رضوی"));
        hometowns.put("076", new Hometown("خواف", "خراسان رضوی"));
        hometowns.put("077", new Hometown("درگز", "خراسان رضوی"));
        hometowns.put("650", new Hometown("رشتخوار", "خراسان رضوی"));
        hometowns.put("574", new Hometown("زبرخان", "خراسان رضوی"));
        hometowns.put("078", new Hometown("سبزوار", "خراسان رضوی"));
        hometowns.put("079", new Hometown("سبزوار", "خراسان رضوی"));
        hometowns.put("081", new Hometown("سرخس", "خراسان رضوی"));
        hometowns.put("084", new Hometown("فریمان", "خراسان رضوی"));
        hometowns.put("651", new Hometown("فیض آباد", "خراسان رضوی"));
        hometowns.put("086", new Hometown("قوچان", "خراسان رضوی"));
        hometowns.put("087", new Hometown("قوچان", "خراسان رضوی"));
        hometowns.put("089", new Hometown("کاشمر", "خراسان رضوی"));
        hometowns.put("090", new Hometown("کاشمر", "خراسان رضوی"));
        hometowns.put("553", new Hometown("کلات", "خراسان رضوی"));
        hometowns.put("091", new Hometown("گناباد", "خراسان رضوی"));
        hometowns.put("092", new Hometown("مشهد", "خراسان رضوی"));
        hometowns.put("093", new Hometown("مشهد", "خراسان رضوی"));
        hometowns.put("094", new Hometown("مشهد", "خراسان رضوی"));
        hometowns.put("097", new Hometown("مشهد منطقه2", "خراسان رضوی"));
        hometowns.put("098", new Hometown("مشهد منطقه3", "خراسان رضوی"));
        hometowns.put("096", new Hometown("مشهد منطقه1", "خراسان رضوی"));
        hometowns.put("105", new Hometown("نیشابور", "خراسان رضوی"));
        hometowns.put("106", new Hometown("نیشابور", "خراسان رضوی"));
        hometowns.put("063", new Hometown("اسفراین", "خراسان شمالی"));
        hometowns.put("067", new Hometown("بجنورد", "خراسان شمالی"));
        hometowns.put("068", new Hometown("بجنورد", "خراسان شمالی"));
        hometowns.put("075", new Hometown("جاجرم", "خراسان شمالی"));
        hometowns.put("591", new Hometown("رازوجرکلان", "خراسان شمالی"));
        hometowns.put("082", new Hometown("شیروان", "خراسان شمالی"));
        hometowns.put("635", new Hometown("فاروج", "خراسان شمالی"));
        hometowns.put("524", new Hometown("مانه و سملقان", "خراسان شمالی"));
        hometowns.put("468", new Hometown("اردل", "چهارمحال و بختیاری"));
        hometowns.put("465", new Hometown("بروجن", "چهارمحال و بختیاری"));
        hometowns.put("461", new Hometown("شهرکرد", "چهارمحال و بختیاری"));
        hometowns.put("462", new Hometown("شهرکرد", "چهارمحال و بختیاری"));
        hometowns.put("467", new Hometown("فارسان", "چهارمحال و بختیاری"));
        hometowns.put("632", new Hometown("فلارد", "چهارمحال و بختیاری"));
        hometowns.put("555", new Hometown("کوهرنگ", "چهارمحال و بختیاری"));
        hometowns.put("633", new Hometown("کیار", "چهارمحال و بختیاری"));
        hometowns.put("629", new Hometown("گندمان", "چهارمحال و بختیاری"));
        hometowns.put("466", new Hometown("لردگان", "چهارمحال و بختیاری"));
        hometowns.put("696", new Hometown("میانکوه", "چهارمحال و بختیاری"));
        hometowns.put("721", new Hometown("بشرویه", "خراسان جنوبی"));
        hometowns.put("064", new Hometown("بیرجند", "خراسان جنوبی"));
        hometowns.put("065", new Hometown("بیرجند", "خراسان جنوبی"));
        hometowns.put("523", new Hometown("درمیان", "خراسان جنوبی"));
        hometowns.put("652", new Hometown("زیرکوه", "خراسان جنوبی"));
        hometowns.put("719", new Hometown("سرایان", "خراسان جنوبی"));
        hometowns.put("716", new Hometown("سربیشه", "خراسان جنوبی"));
        hometowns.put("085", new Hometown("فردوس", "خراسان جنوبی"));
        hometowns.put("088", new Hometown("قائنات", "خراسان جنوبی"));
        hometowns.put("563", new Hometown("نهبندان", "خراسان جنوبی"));
        hometowns.put("529", new Hometown("بندر دیلم", "بوشهر"));
        hometowns.put("353", new Hometown("بندر گناوه", "بوشهر"));
        hometowns.put("349", new Hometown("بوشهر", "بوشهر"));
        hometowns.put("350", new Hometown("بوشهر", "بوشهر"));
        hometowns.put("355", new Hometown("تنگستان", "بوشهر"));
        hometowns.put("609", new Hometown("جم", "بوشهر"));
        hometowns.put("351", new Hometown("دشتستان", "بوشهر"));
        hometowns.put("352", new Hometown("دشتستان", "بوشهر"));
        hometowns.put("354", new Hometown("دشتی", "بوشهر"));
        hometowns.put("732", new Hometown("دلوار", "بوشهر"));
        hometowns.put("357", new Hometown("دیر", "بوشهر"));
        hometowns.put("532", new Hometown("سعد آباد", "بوشهر"));
        hometowns.put("610", new Hometown("شبانکاره", "بوشهر"));
        hometowns.put("356", new Hometown("کنگان", "بوشهر"));
        hometowns.put("556", new Hometown("اسلامشهر", "تهران"));
        hometowns.put("658", new Hometown("پاکدشت", "تهران"));
        hometowns.put("001", new Hometown("تهران مرکزی", "تهران"));
        hometowns.put("002", new Hometown("تهران مرکزی", "تهران"));
        hometowns.put("003", new Hometown("تهران مرکزی", "تهران"));
        hometowns.put("004", new Hometown("تهران مرکزی", "تهران"));
        hometowns.put("005", new Hometown("تهران مرکزی", "تهران"));
        hometowns.put("006", new Hometown("تهران مرکزی", "تهران"));
        hometowns.put("007", new Hometown("تهران مرکزی", "تهران"));
        hometowns.put("008", new Hometown("تهران مرکزی", "تهران"));
        hometowns.put("011", new Hometown("تهران جنوب", "تهران"));
        hometowns.put("020", new Hometown("تهران شرق", "تهران"));
        hometowns.put("025", new Hometown("تهرانشمال", "تهران"));
        hometowns.put("015", new Hometown("تهران غرب", "تهران"));
        hometowns.put("043", new Hometown("دماوند", "تهران"));
        hometowns.put("666", new Hometown("رباط کریم", "تهران"));
        hometowns.put("489", new Hometown("ساوجبلاغ", "تهران"));
        hometowns.put("044", new Hometown("شمیران", "تهران"));
        hometowns.put("045", new Hometown("شمیران", "تهران"));
        hometowns.put("048", new Hometown("شهرری", "تهران"));
        hometowns.put("049", new Hometown("شهرری", "تهران"));
        hometowns.put("490", new Hometown("شهریار", "تهران"));
        hometowns.put("491", new Hometown("شهریار", "تهران"));
        hometowns.put("695", new Hometown("طالقان", "تهران"));
        hometowns.put("659", new Hometown("فیروزکوه", "تهران"));
        hometowns.put("031", new Hometown("کرج", "تهران"));
        hometowns.put("032", new Hometown("کرج", "تهران"));
        hometowns.put("664", new Hometown("کهریزک", "تهران"));
        hometowns.put("717", new Hometown("نظرآباد", "تهران"));
        hometowns.put("041", new Hometown("ورامین", "تهران"));
        hometowns.put("042", new Hometown("ورامین", "تهران"));
        hometowns.put("471", new Hometown("امور خارجه", "امور خارجه"));
        hometowns.put("472", new Hometown("امور خارجه", "امور خارجه"));
        hometowns.put("454", new Hometown("آبدانان", "ایلام"));
        hometowns.put("581", new Hometown("ارکوازی(ملکشاهی)", "ایلام"));
        hometowns.put("449", new Hometown("ایلام", "ایلام"));
        hometowns.put("450", new Hometown("ایلام", "ایلام"));
        hometowns.put("616", new Hometown("ایوان", "ایلام"));
        hometowns.put("534", new Hometown("بدره", "ایلام"));
        hometowns.put("455", new Hometown("دره شهر", "ایلام"));
        hometowns.put("451", new Hometown("دهلران", "ایلام"));
        hometowns.put("726", new Hometown("زرین آباد", "ایلام"));
        hometowns.put("634", new Hometown("شیروان لومار", "ایلام"));
        hometowns.put("453", new Hometown("شیروان و چرداول", "ایلام"));
        hometowns.put("727", new Hometown("موسیان", "ایلام"));
        hometowns.put("452", new Hometown("مهران", "ایلام"));
        hometowns.put("145", new Hometown("اردبیل", "اردبیل"));
        hometowns.put("146", new Hometown("اردبیل", "اردبیل"));
        hometowns.put("731", new Hometown("ارشق", "اردبیل"));
        hometowns.put("690", new Hometown("انگوت", "اردبیل"));
        hometowns.put("601", new Hometown("بیله سوار", "اردبیل"));
        hometowns.put("504", new Hometown("پارس آباد", "اردبیل"));
        hometowns.put("163", new Hometown("خلخال", "اردبیل"));
        hometowns.put("714", new Hometown("خورش رستم", "اردبیل"));
        hometowns.put("715", new Hometown("سرعین", "اردبیل"));
        hometowns.put("566", new Hometown("سنجبد(کوثر)", "اردبیل"));
        hometowns.put("166", new Hometown("مشکین شهر", "اردبیل"));
        hometowns.put("167", new Hometown("مشکین شهر", "اردبیل"));
        hometowns.put("161", new Hometown("مغان", "اردبیل"));
        hometowns.put("162", new Hometown("مغان", "اردبیل"));
        hometowns.put("686", new Hometown("نمین", "اردبیل"));
        hometowns.put("603", new Hometown("نیر", "اردبیل"));
        hometowns.put("619", new Hometown("آران و بیدگل", "اصفهان"));
        hometowns.put("118", new Hometown("اردستان", "اصفهان"));
        hometowns.put("127", new Hometown("اصفهان", "اصفهان"));
        hometowns.put("128", new Hometown("اصفهان", "اصفهان"));
        hometowns.put("129", new Hometown("اصفهان", "اصفهان"));
        hometowns.put("620", new Hometown("باغ بهادران", "اصفهان"));
        hometowns.put("621", new Hometown("بوئین و میاندشت", "اصفهان"));
        hometowns.put("549", new Hometown("تیران و کرون", "اصفهان"));
        hometowns.put("564", new Hometown("جرقویه", "اصفهان"));
        hometowns.put("575", new Hometown("چادگان", "اصفهان"));
        hometowns.put("113", new Hometown("خمینی شهر", "اصفهان"));
        hometowns.put("114", new Hometown("خمینی شهر", "اصفهان"));
        hometowns.put("122", new Hometown("خوانسار", "اصفهان"));
        hometowns.put("540", new Hometown("خور و بیابانک", "اصفهان"));
        hometowns.put("660", new Hometown("دولت آباد", "اصفهان"));
        hometowns.put("120", new Hometown("سمیرم", "اصفهان"));
        hometowns.put("512", new Hometown("سمیرم سفلی (دهاقان)", "اصفهان"));
        hometowns.put("510", new Hometown("شاهین شهر", "اصفهان"));
        hometowns.put("511", new Hometown("شاهین شهر", "اصفهان"));
        hometowns.put("119", new Hometown("شهرضا", "اصفهان"));
        hometowns.put("115", new Hometown("فریدن", "اصفهان"));
        hometowns.put("112", new Hometown("فریدونشهر", "اصفهان"));
        hometowns.put("110", new Hometown("فلاورجان", "اصفهان"));
        hometowns.put("111", new Hometown("فلاورجان", "اصفهان"));
        hometowns.put("125", new Hometown("کاشان", "اصفهان"));
        hometowns.put("126", new Hometown("کاشان", "اصفهان"));
        hometowns.put("565", new Hometown("کوهپایه", "اصفهان"));
        hometowns.put("121", new Hometown("گلپایگان", "اصفهان"));
        hometowns.put("116", new Hometown("لنجان(زرینشهر)", "اصفهان"));
        hometowns.put("117", new Hometown("لنجان(زرینشهر)", "اصفهان"));
        hometowns.put("541", new Hometown("مبارکه", "اصفهان"));
        hometowns.put("622", new Hometown("میمه", "اصفهان"));
        hometowns.put("124", new Hometown("نائین", "اصفهان"));
        hometowns.put("108", new Hometown("نجف آباد", "اصفهان"));
        hometowns.put("109", new Hometown("نجف آباد", "اصفهان"));
        hometowns.put("123", new Hometown("نطنز", "اصفهان"));
        hometowns.put("428", new Hometown("زنجان", "اصفهان"));
        hometowns.put("427", new Hometown("زنجان", "اصفهان"));
        hometowns.put("507", new Hometown("ملکان", "اصفهان"));
        hometowns.put("158", new Hometown("مرند", "اصفهان"));
        hometowns.put("615", new Hometown("ابهر", "اصفهان"));
        hometowns.put("615", new Hometown("خرمدره", "اصفهان"));
        hometowns.put("152", new Hometown("میانه", "اصفهان"));
        hometowns.put("153", new Hometown("میانه", "اصفهان"));
    }
}
